// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGm6QTKtkyoHVoGR-Ea-vuPQFCUdmWUfQ',
    appId: '1:1003962010954:web:07bcd86039f41b697985b3',
    messagingSenderId: '1003962010954',
    projectId: 'final-project-mb-97077',
    authDomain: 'final-project-mb-97077.firebaseapp.com',
    storageBucket: 'final-project-mb-97077.firebasestorage.app',
    measurementId: 'G-ZEJQ9B5E7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCYiHTvgLBdlUIZ8PWdeNmPVyTDzBqxoE',
    appId: '1:1003962010954:android:f777dd7dc209f42e7985b3',
    messagingSenderId: '1003962010954',
    projectId: 'final-project-mb-97077',
    storageBucket: 'final-project-mb-97077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ATCq0e7jByOKgI51ZjbysHRoWdEZWsQ',
    appId: '1:1003962010954:ios:bf7bb22506fd52917985b3',
    messagingSenderId: '1003962010954',
    projectId: 'final-project-mb-97077',
    storageBucket: 'final-project-mb-97077.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ATCq0e7jByOKgI51ZjbysHRoWdEZWsQ',
    appId: '1:1003962010954:ios:bf7bb22506fd52917985b3',
    messagingSenderId: '1003962010954',
    projectId: 'final-project-mb-97077',
    storageBucket: 'final-project-mb-97077.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGm6QTKtkyoHVoGR-Ea-vuPQFCUdmWUfQ',
    appId: '1:1003962010954:web:07bcd86039f41b697985b3',
    messagingSenderId: '1003962010954',
    projectId: 'final-project-mb-97077',
    authDomain: 'final-project-mb-97077.firebaseapp.com',
    storageBucket: 'final-project-mb-97077.firebasestorage.app',
    measurementId: 'G-ZEJQ9B5E7R',
  );
}
