// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1PjOEwHKUyLqs3t68cjeS3_tNDtJBrys',
    appId: '1:890861980931:web:3bcd0b942e1f4c7986ad36',
    messagingSenderId: '890861980931',
    projectId: 'projectstoredatatest-a2cc1',
    authDomain: 'projectstoredatatest-a2cc1.firebaseapp.com',
    storageBucket: 'projectstoredatatest-a2cc1.firebasestorage.app',
    measurementId: 'G-S5594TMV5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaAfnvO0aDavHqOZrytLC1glRtGyfWa_I',
    appId: '1:890861980931:android:92c1aef61caab08c86ad36',
    messagingSenderId: '890861980931',
    projectId: 'projectstoredatatest-a2cc1',
    storageBucket: 'projectstoredatatest-a2cc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwvdgcuSorcNzYzNbM9GGtD4lXO30ymCk',
    appId: '1:890861980931:ios:6e40c528fa9fc25286ad36',
    messagingSenderId: '890861980931',
    projectId: 'projectstoredatatest-a2cc1',
    storageBucket: 'projectstoredatatest-a2cc1.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwvdgcuSorcNzYzNbM9GGtD4lXO30ymCk',
    appId: '1:890861980931:ios:6e40c528fa9fc25286ad36',
    messagingSenderId: '890861980931',
    projectId: 'projectstoredatatest-a2cc1',
    storageBucket: 'projectstoredatatest-a2cc1.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1PjOEwHKUyLqs3t68cjeS3_tNDtJBrys',
    appId: '1:890861980931:web:13263a09b0064dbd86ad36',
    messagingSenderId: '890861980931',
    projectId: 'projectstoredatatest-a2cc1',
    authDomain: 'projectstoredatatest-a2cc1.firebaseapp.com',
    storageBucket: 'projectstoredatatest-a2cc1.firebasestorage.app',
    measurementId: 'G-KRBY0R83YJ',
  );
}
